### ISSUE TITLE
upgrade with Vite Support?

### ISSUE THREAD

**Issue by jiuxiaxixi** [gintsgints/quarkus-fullstack#3]

**Comment by gintsgints** [comment]
Good idea. I think I will work on this.

**Comment by gintsgints** [comment]
@jiuxiaxixi I added vite support at separate branch first. Please check, does it work for you.

**Comment by gintsgints** [comment]
As there is no response, issue is closed as done.

**Comment by jiuxiaxixi** [comment]
Thanks~
